trigger:
  batch: true

jobs:
  - job: "Test"
    strategy:
      matrix:
        Python37Linux:
          imageName: "ubuntu-18.04"
          python.version: "3.7"
        Python37Windows:
          imageName: "vs2017-win2016"
          python.version: "3.7"
        Python37Mac:
          imageName: "macos-10.14"
          python.version: "3.7"
      maxParallel: 4
    pool:
      vmImage: $(imageName)

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
          architecture: "x64"

      - script: |
          pip install -U setuptools wheel
          pip install -r requirements.txt
        displayName: "Install dependencies"

      - script: python setup.py sdist --formats=gztar
        displayName: "Build sdist"

      - task: DeleteFiles@1
        inputs:
          contents: "spacy_lookups_data"
        displayName: "Delete source directory"

      - bash: |
          SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
          pip install dist/$SDIST
        displayName: "Install from sdist"

      - script: python -m pytest --pyargs spacy_lookups_data
        displayName: "Run tests"
